### ISSUE TITLE
iphone XS/XS Max/XR missing models

### ISSUE THREAD

**Issue by kazzmir** [pbakondy/ios-device-list#10]
The entries for iphone xs/xs max/xr do not have any models so none of those iphones are included in the `all` variable in index.js. Thus the following does not return any results:
```
    deviceByInternalName("D331pAP")
```
The issue being that `all` is constructed by iterating over device models.

All the models are available on the wiki: https://www.theiphonewiki.com/wiki/Models

**Comment by pbakondy** [comment]
done
