### ISSUE TITLE
Japanese iPhone 7/7+ models are missing

### ISSUE THREAD

**Issue by sorccu** [pbakondy/ios-device-list#2]
Seems that the https://www.theiphonewiki.com/wiki/Models doesn't contain model numbers for Japanese iPhone 7 versions, and therefore `deviceByModel()` can't be used. I have requested an admin for an account and will add the models to the list when I can. Then hopefully we can update this package :)

By the way what do you personally use this package for?

**Comment by sorccu** [comment]
I've added the Japanese models now. Could you scrape the page again and update the package?

**Comment by pbakondy** [comment]
done

**Comment by sorccu** [comment]
Could you publish to NPM as well?

**Comment by pbakondy** [comment]
done

**Comment by sorccu** [comment]
Works great! Thanks!
