### ISSUE TITLE
"N42AP": "iPhone 5" device missing

### ISSUE THREAD

**Issue by bsergean** [pbakondy/ios-device-list#6]
Sorry I'm too lazy to fill a proper pull request ... but at least I'm reporting this ...

https://www.theiphonewiki.com/wiki/N42AP

**Comment by pbakondy** [comment]
done

**Comment by bsergean** [comment]
Thanks !

I actually found the .json files containing the device list through a google search, so I made a cheap module + python tool to convert them into code that I could use, and then later found out your node module, which I could have used right away ... the irony of life.
