### ISSUE TITLE
Update list for Japanese iPhone X models

### ISSUE THREAD

**Issue by sorccu** [pbakondy/ios-device-list#7]
I just added a few additional iPhone X models to the wiki. Could you pull the data and publish a new version?

Thanks!

**Comment by pbakondy** [comment]
done

**Comment by pbakondy** [comment]
Could you please check issue #5 ?

**Comment by sorccu** [comment]
Thanks! Also, did you maybe forget to push to GitHub? :)

**Comment by pbakondy** [comment]
sure :)
